# Generated by Django 5.2.10 on 2026-02-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbchunk',
            name='embedding_dim',
            field=models.IntegerField(blank=True, help_text='임베딩 차원(예: 1024)', null=True),
        ),
        migrations.AddField(
            model_name='kbchunk',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='임베딩 모델명(예: text-embedding-3-large)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kbchunk',
            name='indexed_at',
            field=models.DateTimeField(blank=True, help_text='Pinecone upsert 완료 시각', null=True),
        ),
        migrations.AlterField(
            model_name='kbchunk',
            name='pinecone_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pinecone vector id (upsert 완료 시 저장)', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='kbchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uq_kbchunk_document_chunkindex'),
        ),
    ]
