# Generated by Django 5.2.10 on 2026-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_no',
            field=models.CharField(db_index=True, default='MIGRATION_TEMP', max_length=30),
            preserve_default=False,
        ),
    ]
