# Generated by Django 5.2.10 on 2026-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_employee_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('HQ', '지주사'), ('OV', '올리브영'), ('DT', '대한통운'), ('JJ', '제일제당'), ('ENM', 'ENM'), ('FD', '푸드빌')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
